#!/bin/sh

python csv_parser_grant.py ../data_raw/ grants APPLICATION_ID SERIAL_NUMBER PROJECT_TITLE ACTIVITY SUPPORT_YEAR SUFFIX FOA_NUMBER PROJECT_START PROJECT_END BUDGET_START BUDGET_END APPLICATION_TYPE CFDA_CODE STUDY_SECTION TOTAL_COST TOTAL_COST_SUB_PROJECT